# syntax=docker/dockerfile:1.7
FROM node:20-alpine

WORKDIR /frontend

COPY frontend-preguntas/package*.json ./
RUN --mount=type=cache,target=/root/.npm npm ci
COPY frontend-preguntas/ .

EXPOSE 3003

CMD ["npm", "run", "dev"]
